[2025-02-15T01:50:30.537+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_ETL.get_location_dict manual__2025-02-15T01:50:23.485590+00:00 [queued]>
[2025-02-15T01:50:30.664+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_ETL.get_location_dict manual__2025-02-15T01:50:23.485590+00:00 [queued]>
[2025-02-15T01:50:30.668+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-02-15T01:50:30.728+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): get_location_dict> on 2025-02-15 01:50:23.485590+00:00
[2025-02-15T01:50:30.736+0000] {standard_task_runner.py:57} INFO - Started process 38 to run task
[2025-02-15T01:50:30.743+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'weather_data_ETL', 'get_location_dict', 'manual__2025-02-15T01:50:23.485590+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpy2239ih4']
[2025-02-15T01:50:30.747+0000] {standard_task_runner.py:85} INFO - Job 84: Subtask get_location_dict
[2025-02-15T01:50:30.860+0000] {task_command.py:410} INFO - Running <TaskInstance: weather_data_ETL.get_location_dict manual__2025-02-15T01:50:23.485590+00:00 [running]> on host cbea98f91475
[2025-02-15T01:50:31.145+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='weather_data_ETL' AIRFLOW_CTX_TASK_ID='get_location_dict' AIRFLOW_CTX_EXECUTION_DATE='2025-02-15T01:50:23.485590+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-15T01:50:23.485590+00:00'
[2025-02-15T01:50:31.328+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-02-15T01:50:31.366+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=weather_data_ETL, task_id=get_location_dict, execution_date=20250215T015023, start_date=20250215T015030, end_date=20250215T015031
[2025-02-15T01:50:31.473+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-02-15T01:50:31.561+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
